import * as React from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {ArrowPathIcon,BookOpenIcon,CalendarDaysIcon,CheckCircleIcon,ExclamationTriangleIcon,PencilSquareIcon,PlusIcon,TrashIcon,XMarkIcon} from "@heroicons/react/24/outline";
import {useNavigate} from "react-router-dom";
import {createCurriculum,deleteCurriculum,fetchAllCurriculums,setCurriculumIndicators} from "../../../api/administrasi";
import {fetchCurrentAcademicPeriod} from "../../../api/academic-periods";
import {SectionHeader} from "../../../components/common/DesignSystem";
import {adminQueryKeys} from "../../../lib/adminQueryKeys";
import {apiErrorMessage} from "../../../lib/apiError";

const text=value=>String(value??"").trim(),keyOf=value=>String(value??"");
const baseName=value=>{const raw=text(typeof value==="object"&&value!==null?value.nama_kurikulum:value);return raw.replace(/\s*·\s*Penetapan\s+20\d{2}\s*[/-]\s*20\d{2}(?:\s+#\d+)?\s*$/i,"").trim()||raw||"Kurikulum";};
const periodLabel=period=>period?`${text(period.tahun_ajaran)||"-"} · Semester ${Number(period.semester)||"-"}`:"Belum ada periode aktif";
const nextName=(source,year,items)=>{const base=baseName(source),used=new Set(items.map(item=>text(item.nama_kurikulum).toLowerCase()).filter(Boolean)),first=`${base} · Penetapan ${year}`;if(!used.has(first.toLowerCase()))return first;for(let i=2;i<10000;i++){const candidate=`${first} #${i}`;if(!used.has(candidate.toLowerCase()))return candidate;}throw new Error("Tidak dapat membuat nama penetapan kurikulum yang unik.");};
const byNewest=(a,b)=>{const ai=Number(a?.id),bi=Number(b?.id);if(Number.isFinite(ai)&&Number.isFinite(bi)&&ai!==bi)return bi-ai;return text(b?.tahun_ajaran).localeCompare(text(a?.tahun_ajaran),"id",{numeric:true,sensitivity:"base"});};

function ActionPopup({dialog,onClose}){if(!dialog)return null;const success=dialog.tone==="success",warning=dialog.tone==="warning",Icon=success?CheckCircleIcon:ExclamationTriangleIcon,iconClass=success?"bg-emerald-50 text-emerald-600":warning?"bg-amber-50 text-amber-600":"bg-rose-50 text-rose-500",buttonClass=success?"bg-emerald-600 hover:bg-emerald-700":warning?"bg-amber-500 hover:bg-amber-600":"bg-rose-500 hover:bg-rose-600";return <div className="fixed inset-0 z-70 flex items-end justify-center bg-slate-950/35 p-0 backdrop-blur-[2px] sm:items-center sm:p-4" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section role="dialog" aria-modal="true" className="w-full rounded-t-2xl border border-slate-100 bg-white shadow-2xl sm:max-w-md sm:rounded-xl"><div className="p-5"><div className="flex items-start gap-3"><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-lg ${iconClass}`}><Icon className="h-[18px] w-[18px]"/></span><div className="min-w-0 flex-1"><h2 className="text-[13px] font-semibold text-slate-800">{dialog.title}</h2><p className="mt-1 text-[11px] leading-5 text-slate-500">{dialog.description}</p></div><button type="button" onClick={onClose} className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100 hover:text-slate-600"><XMarkIcon className="h-4 w-4"/></button></div><div className="mt-5 flex justify-end"><button type="button" onClick={onClose} className={`h-9 rounded-lg px-4 text-[11px] font-semibold text-white ${buttonClass}`}>{success?"Selesai":"Tutup"}</button></div></div></section></div>;}
function ConfirmPopup({dialog,onClose,onConfirm,busy}){if(!dialog)return null;return <div className="fixed inset-0 z-70 flex items-end justify-center bg-slate-950/35 p-0 backdrop-blur-[2px] sm:items-center sm:p-4" onMouseDown={event=>event.target===event.currentTarget&&!busy&&onClose()}><section role="dialog" aria-modal="true" className="w-full rounded-t-2xl border border-slate-100 bg-white shadow-2xl sm:max-w-md sm:rounded-xl"><div className="p-5"><div className="flex items-start gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-red-50 text-[#ef4d45]"><ArrowPathIcon className="h-[18px] w-[18px]"/></span><div className="min-w-0 flex-1"><h2 className="text-[13px] font-semibold text-slate-800">Aktifkan Kurikulum?</h2><p className="mt-1 text-[11px] leading-5 text-slate-500">Sistem membuat penetapan baru untuk periode aktif dan menyalin struktur indikator dari kurikulum ini.</p></div><button type="button" onClick={onClose} disabled={busy} className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100 disabled:opacity-40"><XMarkIcon className="h-4 w-4"/></button></div><dl className="mt-4 divide-y divide-slate-100 rounded-lg border border-slate-100 bg-slate-50/50 px-3"><div className="flex items-center justify-between gap-4 py-2.5"><dt className="text-[10px] text-slate-400">Kurikulum</dt><dd className="text-right text-[10px] font-semibold text-slate-600">{baseName(dialog.source)}</dd></div><div className="flex items-center justify-between gap-4 py-2.5"><dt className="text-[10px] text-slate-400">Periode Tujuan</dt><dd className="text-right text-[10px] font-semibold text-slate-600">{periodLabel(dialog.period)}</dd></div><div className="flex items-center justify-between gap-4 py-2.5"><dt className="text-[10px] text-slate-400">Indikator</dt><dd className="text-right text-[10px] font-semibold text-slate-600">{dialog.source.indikator_ids?.length||0} indikator</dd></div></dl><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} disabled={busy} className="ui-toolbar-button">Batal</button><button type="button" onClick={onConfirm} disabled={busy} className="inline-flex h-9 items-center gap-2 rounded-lg bg-[#ef4d45] px-4 text-[11px] font-semibold text-white hover:bg-[#df433c] disabled:opacity-50">{busy&&<ArrowPathIcon className="h-3.5 w-3.5 animate-spin"/>}{busy?"Memproses...":"Aktifkan"}</button></div></div></section></div>;}
function DeletePopup({dialog,onClose,onConfirm,busy}){if(!dialog)return null;return <div className="fixed inset-0 z-70 flex items-end justify-center bg-slate-950/35 p-0 backdrop-blur-[2px] sm:items-center sm:p-4" onMouseDown={event=>event.target===event.currentTarget&&!busy&&onClose()}><section role="dialog" aria-modal="true" className="w-full rounded-t-2xl border border-slate-100 bg-white shadow-2xl sm:max-w-md sm:rounded-xl"><div className="p-5"><div className="flex items-start gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-rose-50 text-rose-500"><TrashIcon className="h-[18px] w-[18px]"/></span><div className="min-w-0 flex-1"><h2 className="text-[13px] font-semibold text-slate-800">Hapus Kurikulum?</h2><p className="mt-1 text-[11px] leading-5 text-slate-500">Kurikulum akan dihapus permanen jika backend mendukung penghapusan. Tindakan ini tidak dapat dibatalkan.</p></div><button type="button" onClick={onClose} disabled={busy} className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100 disabled:opacity-40"><XMarkIcon className="h-4 w-4"/></button></div><dl className="mt-4 divide-y divide-slate-100 rounded-lg border border-slate-100 bg-slate-50/50 px-3"><div className="flex items-center justify-between gap-4 py-2.5"><dt className="text-[10px] text-slate-400">Kurikulum</dt><dd className="text-right text-[10px] font-semibold text-slate-600">{baseName(dialog)}</dd></div><div className="flex items-center justify-between gap-4 py-2.5"><dt className="text-[10px] text-slate-400">Tahun Ajar</dt><dd className="text-right text-[10px] font-semibold text-slate-600">{text(dialog.tahun_ajaran)||"-"}</dd></div><div className="flex items-center justify-between gap-4 py-2.5"><dt className="text-[10px] text-slate-400">Indikator</dt><dd className="text-right text-[10px] font-semibold text-slate-600">{dialog.indikator_ids?.length||0} indikator</dd></div></dl><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} disabled={busy} className="ui-toolbar-button">Batal</button><button type="button" onClick={onConfirm} disabled={busy} className="inline-flex h-9 items-center gap-2 rounded-lg bg-rose-500 px-4 text-[11px] font-semibold text-white hover:bg-rose-600 disabled:opacity-50">{busy&&<ArrowPathIcon className="h-3.5 w-3.5 animate-spin"/>}{busy?"Menghapus...":"Hapus Kurikulum"}</button></div></div></section></div>;}

export default function Kurikulum(){
  const navigate=useNavigate(),queryClient=useQueryClient();
  const [addOpen,setAddOpen]=React.useState(false),[name,setName]=React.useState(""),[dialog,setDialog]=React.useState(null),[confirm,setConfirm]=React.useState(null),[deleteConfirm,setDeleteConfirm]=React.useState(null);
  const periodQuery=useQuery({queryKey:adminQueryKeys.academicPeriod,queryFn:({signal})=>fetchCurrentAcademicPeriod(signal),staleTime:5*60_000});
  const curriculumQuery=useQuery({queryKey:adminQueryKeys.curriculums,queryFn:({signal})=>fetchAllCurriculums(100,signal),staleTime:5*60_000});
  const createMutation=useMutation({mutationFn:payload=>createCurriculum(payload)});
  const deleteMutation=useMutation({mutationFn:id=>deleteCurriculum(id)});
  const reactivateMutation=useMutation({mutationFn:async({source,period,items})=>{const year=text(period.tahun_ajaran),created=await createCurriculum({nama_kurikulum:nextName(source,year,items),tahun_ajaran:year,deskripsi:`Ditetapkan kembali dari ${baseName(source)} untuk ${periodLabel(period)}`,status_aktif:true,mata_pelajaran:Array.isArray(source.mata_pelajaran)?source.mata_pelajaran:[]});if(created?.id==null)throw new Error("ID kurikulum baru tidak ditemukan.");if(source.indikator_ids?.length)await setCurriculumIndicators(created.id,source.indikator_ids);return created;}});
  const period=periodQuery.data??null,year=text(period?.tahun_ajaran),items=React.useMemo(()=>[...(Array.isArray(curriculumQuery.data)?curriculumQuery.data:[])].sort(byNewest),[curriculumQuery.data]);
  const active=React.useMemo(()=>items.filter(item=>item.status_aktif===true&&text(item.tahun_ajaran)===year).sort(byNewest)[0]??null,[items,year]);
  const history=React.useMemo(()=>items.filter(item=>!active||keyOf(item.id)!==keyOf(active.id)),[items,active]);
  const loading=periodQuery.isPending||curriculumQuery.isPending,loadError=periodQuery.isError?apiErrorMessage(periodQuery.error,{action:"memuat",subject:"periode akademik"}):curriculumQuery.isError?apiErrorMessage(curriculumQuery.error,{action:"memuat",subject:"kurikulum"}):"";
  const invalidate=()=>Promise.all([queryClient.invalidateQueries({queryKey:adminQueryKeys.curriculums}),queryClient.invalidateQueries({queryKey:["kegiatan"]})]);
  const openEdit=item=>item?.id!=null&&navigate(`/administrasi/kurikulum/${item.id}/edit`);
  const create=async event=>{event.preventDefault();const curriculumName=text(name);if(!curriculumName||!year||createMutation.isPending)return;try{const created=await createMutation.mutateAsync({nama_kurikulum:curriculumName,tahun_ajaran:year,deskripsi:`Kurikulum untuk periode ${periodLabel(period)}`,status_aktif:true,mata_pelajaran:[]});await invalidate();setAddOpen(false);setName("");if(created?.id!=null)navigate(`/administrasi/kurikulum/${created.id}/edit`,{state:{created:true}});else setDialog({tone:"success",title:"Kurikulum Berhasil Dibuat",description:`${curriculumName} berhasil dibuat untuk ${periodLabel(period)}.`});}catch(error){setDialog({tone:"danger",title:"Kurikulum Gagal Dibuat",description:apiErrorMessage(error,{action:"membuat",subject:"kurikulum"})});}};
  const activate=async()=>{const pending=confirm;if(!pending||reactivateMutation.isPending)return;try{const created=await reactivateMutation.mutateAsync({source:pending.source,period:pending.period,items});await invalidate();setConfirm(null);setDialog({tone:"success",title:"Kurikulum Berhasil Diaktifkan",description:`${baseName(created)} sekarang menjadi penetapan terbaru untuk ${periodLabel(period)}.`});}catch(error){setConfirm(null);setDialog({tone:"danger",title:"Kurikulum Gagal Diaktifkan",description:apiErrorMessage(error,{action:"mengaktifkan",subject:"kurikulum"})});}};
  const remove=async()=>{const pending=deleteConfirm;if(!pending?.id||deleteMutation.isPending)return;try{await deleteMutation.mutateAsync(pending.id);await invalidate();setDeleteConfirm(null);setDialog({tone:"success",title:"Kurikulum Berhasil Dihapus",description:`${baseName(pending)} berhasil dihapus dari riwayat kurikulum.`});}catch(error){setDeleteConfirm(null);const status=Number(error?.status)||0;if([404,405,501].includes(status))setDialog({tone:"warning",title:"Hapus Kurikulum Belum Tersedia",description:"Backend saat ini belum menyediakan endpoint hapus kurikulum, atau kurikulum sudah tidak tersedia. Tidak ada data yang dihapus."});else setDialog({tone:"danger",title:"Kurikulum Gagal Dihapus",description:apiErrorMessage(error,{action:"menghapus",subject:"kurikulum"})});}};
  return <div className="space-y-5 animate-in fade-in duration-300">
    <SectionHeader icon={BookOpenIcon} title="Kurikulum" description="Kelola kurikulum periode aktif dan atur struktur aspek, sub aspek, serta indikator pada halaman terpisah." actions={<><span className="text-[10px] text-slate-400"><b className="font-semibold text-slate-600">{items.length}</b> kurikulum</span><button type="button" onClick={()=>setAddOpen(true)} disabled={!period||createMutation.isPending} className="inline-flex h-9 items-center gap-2 rounded-lg bg-[#ef4d45] px-4 text-xs font-semibold text-white hover:bg-[#df433c] disabled:cursor-not-allowed disabled:opacity-50"><PlusIcon className="h-4 w-4"/>Tambah Kurikulum</button></>}/>
    <div className="flex flex-col gap-3 rounded-xl border border-slate-200 bg-white px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-slate-50 text-slate-400"><CalendarDaysIcon className="h-[18px] w-[18px]"/></span><div><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">Periode Akademik Aktif</p><p className="mt-0.5 text-[12px] font-semibold text-slate-700">{loading?"Memuat...":periodLabel(period)}</p></div></div>{period&&<span className="text-[10px] text-slate-400">{text(period.nama_periode)||"Periode berjalan"}</span>}</div>
    {loadError?<div className="rounded-xl border border-rose-100 bg-rose-50/60 p-4"><p className="text-[11px] font-medium text-rose-600">{loadError}</p><button type="button" onClick={()=>Promise.all([periodQuery.refetch(),curriculumQuery.refetch()])} className="ui-toolbar-button mt-3"><ArrowPathIcon className="h-4 w-4"/>Muat Ulang</button></div>:<>
      <section className="space-y-3"><div><h2 className="text-[12px] font-semibold text-slate-700">Kurikulum Digunakan Saat Ini</h2><p className="mt-0.5 text-[10px] text-slate-400">Kurikulum aktif untuk tahun ajar pada periode akademik yang sedang berjalan.</p></div>{loading?<div className="h-32 animate-pulse rounded-xl border border-slate-200 bg-slate-50"/>:active?<div className="rounded-xl border border-red-100 bg-red-50/30 p-4"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate text-[14px] font-semibold text-slate-800">{baseName(active)}</h3><span className="rounded-full border border-emerald-100 bg-emerald-50 px-2 py-0.5 text-[9px] font-semibold text-emerald-600">Aktif</span></div><p className="mt-1 text-[10px] text-slate-400">{text(active.tahun_ajaran)||"-"} · {active.indikator_ids?.length||0} indikator terpilih</p>{text(active.deskripsi)&&<p className="mt-2 max-w-3xl text-[11px] leading-5 text-slate-500">{text(active.deskripsi)}</p>}</div><button type="button" onClick={()=>openEdit(active)} className="ui-toolbar-button shrink-0"><PencilSquareIcon className="h-4 w-4"/>Atur Struktur</button></div></div>:<div className="rounded-xl border border-dashed border-slate-200 bg-white px-5 py-8 text-center"><BookOpenIcon className="mx-auto h-6 w-6 text-slate-300"/><p className="mt-2 text-[11px] font-semibold text-slate-600">Belum ada kurikulum aktif</p><p className="mt-1 text-[10px] text-slate-400">Tambahkan kurikulum untuk periode aktif agar dapat digunakan pada Data Kelas.</p></div>}</section>
      <section className="space-y-3"><div><h2 className="text-[12px] font-semibold text-slate-700">Riwayat Kurikulum</h2><p className="mt-0.5 text-[10px] text-slate-400">Kurikulum lama tetap tersimpan dan dapat ditinjau, diedit strukturnya, atau ditetapkan kembali.</p></div><div className="ui-table-card overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[760px]"><thead><tr className="border-b border-slate-100 bg-slate-50/70"><th className="w-12 px-3 py-2.5 text-center text-[10px] font-semibold uppercase tracking-wide text-slate-400">No</th><th className="px-3 py-2.5 text-left text-[10px] font-semibold uppercase tracking-wide text-slate-400">Kurikulum</th><th className="w-32 px-3 py-2.5 text-left text-[10px] font-semibold uppercase tracking-wide text-slate-400">Tahun Ajar</th><th className="w-24 px-3 py-2.5 text-center text-[10px] font-semibold uppercase tracking-wide text-slate-400">Indikator</th><th className="px-3 py-2.5 text-left text-[10px] font-semibold uppercase tracking-wide text-slate-400">Keterangan</th><th className="w-44 px-3 py-2.5 text-right text-[10px] font-semibold uppercase tracking-wide text-slate-400">Aksi</th></tr></thead><tbody>{loading?<tr><td colSpan={6} className="px-3 py-8 text-center text-[11px] text-slate-400">Memuat riwayat kurikulum...</td></tr>:history.length===0?<tr><td colSpan={6} className="px-3 py-8 text-center text-[11px] text-slate-400">Belum ada riwayat kurikulum.</td></tr>:history.map((item,index)=>{const sameYear=text(item.tahun_ajaran)===year;return <tr key={keyOf(item.id)} className="border-b border-slate-100 last:border-b-0 hover:bg-slate-50/60"><td className="px-3 py-2.5 text-center text-[11px] text-slate-400">{index+1}</td><td className="px-3 py-2.5"><p className="text-[11px] font-semibold text-slate-700">{baseName(item)}</p></td><td className="px-3 py-2.5 text-[11px] text-slate-500">{text(item.tahun_ajaran)||"-"}</td><td className="px-3 py-2.5 text-center text-[11px] font-medium text-slate-600">{item.indikator_ids?.length||0}</td><td className="max-w-xs px-3 py-2.5"><p className="truncate text-[11px] text-slate-500">{text(item.deskripsi)||"-"}</p></td><td className="px-3 py-2.5"><div className="flex items-center justify-end gap-2"><button type="button" onClick={()=>openEdit(item)} className="ui-action-button"><PencilSquareIcon/>Atur Struktur</button>{period&&(!sameYear||!active||keyOf(item.id)!==keyOf(active.id))&&<button type="button" onClick={()=>setConfirm({source:item,period})} className="ui-action-button"><CheckCircleIcon/>Aktifkan</button>}<button type="button" onClick={()=>setDeleteConfirm(item)} className="ui-action-button text-rose-500 hover:border-rose-100 hover:bg-rose-50 hover:text-rose-600"><TrashIcon/>Hapus</button></div></td></tr>;})}</tbody></table></div></div></section>
    </>}
    {addOpen&&<div className="fixed inset-0 z-60 flex items-end justify-center bg-slate-950/35 p-0 backdrop-blur-[2px] sm:items-center sm:p-4" onMouseDown={event=>event.target===event.currentTarget&&!createMutation.isPending&&setAddOpen(false)}><section role="dialog" aria-modal="true" className="w-full rounded-t-2xl border border-slate-100 bg-white shadow-2xl sm:max-w-md sm:rounded-xl"><form onSubmit={create} className="p-5"><div className="flex items-start gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-red-50 text-[#ef4d45]"><PlusIcon className="h-[18px] w-[18px]"/></span><div className="min-w-0 flex-1"><h2 className="text-[13px] font-semibold text-slate-800">Tambah Kurikulum</h2><p className="mt-1 text-[11px] leading-5 text-slate-500">Kurikulum baru dibuat untuk {periodLabel(period)} dan setelah tersimpan Anda akan diarahkan untuk memilih strukturnya.</p></div><button type="button" onClick={()=>setAddOpen(false)} disabled={createMutation.isPending} className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100 disabled:opacity-40"><XMarkIcon className="h-4 w-4"/></button></div><div className="mt-4"><label className="mb-1.5 block text-[10px] font-semibold uppercase tracking-wide text-slate-400">Nama Kurikulum</label><input autoFocus required value={name} onChange={event=>setName(event.target.value)} disabled={createMutation.isPending} placeholder="Contoh: Kurikulum Merdeka" className="ui-compact-control w-full"/></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>setAddOpen(false)} disabled={createMutation.isPending} className="ui-toolbar-button">Batal</button><button type="submit" disabled={createMutation.isPending||!text(name)||!period} className="inline-flex h-9 items-center gap-2 rounded-lg bg-[#ef4d45] px-4 text-[11px] font-semibold text-white hover:bg-[#df433c] disabled:opacity-50">{createMutation.isPending&&<ArrowPathIcon className="h-3.5 w-3.5 animate-spin"/>}{createMutation.isPending?"Menyimpan...":"Buat & Atur Struktur"}</button></div></form></section></div>}
    <ConfirmPopup dialog={confirm} onClose={()=>setConfirm(null)} onConfirm={activate} busy={reactivateMutation.isPending}/><DeletePopup dialog={deleteConfirm} onClose={()=>setDeleteConfirm(null)} onConfirm={remove} busy={deleteMutation.isPending}/><ActionPopup dialog={dialog} onClose={()=>setDialog(null)}/>
  </div>;
}
