import {Check,CheckCircle2,LockKeyhole,RefreshCcw,RotateCcw,Save,ShieldCheck,TriangleAlert,X} from "lucide-react";
import {useEffect,useMemo,useState} from "react";
import {fetchStaff} from "../../api/staff";
import {ACCESS_FEATURES,ACCESS_POSITION_PRESETS,accessPositionKey,defaultAccessForPosition,getAccessControlConfig,isAccessPositionLocked,resetAccessControlConfig,saveAccessControlConfig} from "../../auth/accessControl";
import {SectionHeader} from "../../components/common/DesignSystem";
import {apiErrorMessage} from "../../lib/apiError";

function Toggle({checked,disabled,onChange,label}){return <button type="button" disabled={disabled} onClick={()=>!disabled&&onChange(!checked)} aria-label={label} aria-pressed={checked} className={`inline-flex h-7 min-w-14 items-center justify-center gap-1 rounded-lg border px-2 text-[10px] font-semibold transition ${disabled?"cursor-not-allowed border-slate-100 bg-slate-50 text-slate-300":checked?"border-red-100 bg-red-50 text-[#ef4d45]":"border-slate-200 bg-white text-slate-400 hover:bg-slate-50"}`}>{disabled?<LockKeyhole className="h-3 w-3"/>:checked?<Check className="h-3 w-3"/>:null}{checked?"Aktif":"Nonaktif"}</button>;}
function Confirm({open,onClose,onConfirm}){if(!open)return null;return <div className="fixed inset-0 z-100 flex items-center justify-center bg-slate-950/40 p-4 backdrop-blur-[2px]" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><div role="dialog" aria-modal="true" className="w-full max-w-sm overflow-hidden rounded-xl bg-white shadow-2xl"><header className="flex items-start justify-between gap-3 border-b border-slate-100 px-4 py-3"><div><h3 className="text-[13px] font-semibold text-slate-800">Reset Hak Akses</h3><p className="mt-1 text-[10px] leading-4 text-slate-400">Kembalikan seluruh jabatan ke konfigurasi default?</p></div><button type="button" onClick={onClose} className="flex h-7 w-7 items-center justify-center rounded-lg text-slate-400 hover:bg-slate-100"><X className="h-4 w-4"/></button></header><footer className="flex justify-end gap-2 px-4 py-3"><button type="button" onClick={onClose} className="ui-toolbar-button">Batal</button><button type="button" onClick={onConfirm} className="ui-toolbar-button is-active"><RotateCcw className="h-4 w-4"/>Reset</button></footer></div></div>;}
function ResultPopup({data,onClose}){if(!data)return null;const success=data.type==="success",Icon=success?CheckCircle2:TriangleAlert;return <div className="fixed inset-0 z-110 flex items-center justify-center bg-slate-950/40 p-4 backdrop-blur-[2px]" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><div role="dialog" aria-modal="true" className="w-full max-w-sm overflow-hidden rounded-xl bg-white shadow-2xl"><div className="flex gap-3 px-4 py-4"><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-lg border ${success?"border-emerald-100 bg-emerald-50 text-emerald-500":"border-red-100 bg-red-50 text-red-500"}`}><Icon className="h-5 w-5"/></span><div className="min-w-0 flex-1"><h3 className="text-[13px] font-semibold text-slate-800">{data.title}</h3><p className="mt-1 text-[10px] leading-4 text-slate-500">{data.message}</p></div><button type="button" onClick={onClose} className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg text-slate-400 hover:bg-slate-100"><X className="h-4 w-4"/></button></div><footer className="flex justify-end border-t border-slate-100 px-4 py-3"><button type="button" onClick={onClose} className={`ui-toolbar-button ${success?"":"is-active"}`}>Tutup</button></footer></div></div>;}

export default function AccessControlTab(){
  const [positions,setPositions]=useState([]),[counts,setCounts]=useState({}),[config,setConfig]=useState(()=>getAccessControlConfig()),[loading,setLoading]=useState(true),[error,setError]=useState(""),[saved,setSaved]=useState(true),[confirmReset,setConfirmReset]=useState(false),[result,setResult]=useState(null);
  const load=async()=>{setLoading(true);setError("");try{const staff=await fetchStaff({limit:100}),map=new Map();for(const item of staff){const label=String(item?.jabatan??"").trim();if(!label)continue;const key=accessPositionKey(label),current=map.get(key);map.set(key,{key,label:current?.label||label,count:(current?.count||0)+1});}const preset=ACCESS_POSITION_PRESETS.map(label=>{const key=accessPositionKey(label),detected=map.get(key);map.delete(key);return{key,label,count:detected?.count||0};}),extras=[...map.values()].sort((a,b)=>a.label.localeCompare(b.label,"id")),next=[...preset,...extras];setPositions(next);setCounts(Object.fromEntries(next.map(item=>[item.key,item.count])));setConfig(current=>{const merged=getAccessControlConfig(next.map(item=>item.label));for(const [key,value] of Object.entries(current.positions??{}))if(merged.positions[key])merged.positions[key]=value;return merged;});}catch(err){const fallback=ACCESS_POSITION_PRESETS.map(label=>({key:accessPositionKey(label),label,count:0}));setPositions(fallback);setCounts(Object.fromEntries(fallback.map(item=>[item.key,0])));setConfig(getAccessControlConfig(fallback.map(item=>item.label)));setError(apiErrorMessage(err,{action:"memuat",subject:"jabatan staff"}));}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  const activeCounts=useMemo(()=>Object.fromEntries(positions.map(position=>[position.key,ACCESS_FEATURES.filter(feature=>(config.positions?.[position.key]??defaultAccessForPosition(position.label))[feature.id]).length])),[config,positions]);
  const change=(position,feature,value)=>{if(isAccessPositionLocked(position.label))return;setConfig(current=>({...current,positions:{...current.positions,[position.key]:{...(current.positions?.[position.key]??defaultAccessForPosition(position.label)),[feature]:value}}}));setSaved(false);};
  const save=()=>{try{const next=saveAccessControlConfig(config);setConfig(next);setSaved(true);setResult({type:"success",title:"Hak Akses Berhasil Diubah",message:"Perubahan hak akses berdasarkan jabatan berhasil disimpan dan langsung diterapkan pada navigasi serta route frontend."});}catch(err){setSaved(false);setResult({type:"error",title:"Hak Akses Gagal Diubah",message:apiErrorMessage(err,{action:"menyimpan",subject:"hak akses"})});}};
  const reset=()=>{try{setConfig(resetAccessControlConfig(positions.map(item=>item.label)));setSaved(true);setConfirmReset(false);setResult({type:"success",title:"Hak Akses Berhasil Direset",message:"Seluruh hak akses berdasarkan jabatan berhasil dikembalikan ke konfigurasi default."});}catch(err){setConfirmReset(false);setResult({type:"error",title:"Hak Akses Gagal Direset",message:apiErrorMessage(err,{action:"mereset",subject:"hak akses"})});}};
  const actions=<><button type="button" onClick={load} disabled={loading} className="ui-toolbar-button"><RefreshCcw className={`h-4 w-4 ${loading?"animate-spin":""}`}/>Muat Ulang</button><button type="button" onClick={()=>setConfirmReset(true)} className="ui-toolbar-button"><RotateCcw className="h-4 w-4"/>Reset Default</button><button type="button" onClick={save} disabled={saved} className={`ui-toolbar-button ${!saved?"is-active":"opacity-50"}`}><Save className="h-4 w-4"/>Simpan</button></>;
  return <div className="space-y-4"><SectionHeader icon={ShieldCheck} title="Access Control" description="Atur akses modul berdasarkan jabatan staff yang terdaftar di sistem." actions={actions}/><div className="grid gap-2 sm:grid-cols-2"><div className="rounded-lg border border-slate-200 bg-white px-3 py-2.5"><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">Jabatan Tersedia</p><p className="mt-1 text-[13px] font-semibold text-slate-700">{positions.length} jabatan</p></div><div className="rounded-lg border border-slate-200 bg-white px-3 py-2.5"><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">Akses Tetap</p><p className="mt-1 text-[11px] font-medium text-slate-600">Admin, Kepala Sekolah dan Ketua Yayasan memiliki akses penuh.</p></div></div>{error&&<div className="rounded-lg border border-amber-100 bg-amber-50/60 px-3 py-2 text-[10px] leading-4 text-amber-700">{error} Daftar jabatan default digunakan sementara.</div>}<section className="ui-table-card overflow-x-auto mt-4"><table className="w-full min-w-275"><thead><tr><th className="sticky left-0 z-10 min-w-44 bg-slate-50 text-left">Jabatan</th>{ACCESS_FEATURES.map(feature=><th key={feature.id} className="min-w-28 text-center">{feature.label}</th>)}</tr></thead><tbody>{loading&&!positions.length?<tr><td colSpan={ACCESS_FEATURES.length+1} className="px-3 py-8 text-center text-[11px] text-slate-400">Memuat jabatan...</td></tr>:positions.map(position=>{const locked=isAccessPositionLocked(position.label),features=config.positions?.[position.key]??defaultAccessForPosition(position.label);return <tr key={position.key}><td className="sticky left-0 z-10 bg-white"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="truncate text-[11px] font-semibold text-slate-700">{position.label}</p><p className="mt-0.5 text-[9px] text-slate-400">{counts[position.key]||0} staff · {activeCounts[position.key]||0}/{ACCESS_FEATURES.length} modul</p></div>{locked&&<LockKeyhole className="h-3.5 w-3.5 shrink-0 text-slate-300"/>}</div></td>{ACCESS_FEATURES.map(feature=><td key={feature.id} className="text-center"><Toggle checked={locked?true:Boolean(features[feature.id])} disabled={locked} onChange={value=>change(position,feature.id,value)} label={`${position.label} ${feature.label}`}/></td>)}</tr>;})}</tbody></table></section><div className="rounded-lg border border-amber-100 bg-amber-50/60 px-3 py-2 text-[10px] leading-4 text-amber-700">Pengaturan ini mengontrol navigasi dan route frontend berdasarkan jabatan dari profil pengguna. Role backend Admin tetap full access. Otorisasi endpoint tetap harus divalidasi backend.</div><Confirm open={confirmReset} onClose={()=>setConfirmReset(false)} onConfirm={reset}/><ResultPopup data={result} onClose={()=>setResult(null)}/></div>;
}
